### ISSUE TITLE
Connect this Example or sdk to Ionic

### ISSUE THREAD

**Issue by gvmarvelos** [IndoorAtlas/sdk-cordova-examples#18]
Hello I am trying to connect this sdk to Ionic, could someone help me? The SDK or directly use the example. I have made several attempts but I have not been successful. Thank you.

**Comment by oseiskar** [comment]
Ionic is not officially supported. In order to receive helpful answers to your question, you must make it more specific. What did you try and what problems (error messages etc.) did you encounter. This is not a good forum for receiving instructions to developing a completely new integration
